package builtin

var AnimalsSimple = Group{
	Name: "animals - simple",
	Words: []Word{
		{English: "cat", Chinese: "猫"},
		{English: "dog", Chinese: "狗"},
		{English: "pig", Chinese: "猪"},
		{English: "duck", Chinese: "鸭"},
		{English: "rabbit", Chinese: "兔子"},
		{English: "horse", Chinese: "马"},
		{English: "elephant", Chinese: "大象"},
		{English: "ant", Chinese: "蚂蚁"},
		{English: "fish", Chinese: "鱼"},
		{English: "bird", Chinese: "鸟"},
		{English: "snake", Chinese: "蛇"},
		{English: "kangaroo", Chinese: "袋鼠"},
		{English: "monkey", Chinese: "猴子"},
		{English: "panda", Chinese: "熊猫"},
		{English: "bear", Chinese: "熊"},
		{English: "lion", Chinese: "狮"},
		{English: "tiger", Chinese: "老虎"},
		{English: "fox", Chinese: "狐狸"},
		{English: "zebra", Chinese: "斑马"},
		{English: "deer", Chinese: "鹿"},
		{English: "giraffe", Chinese: "长颈鹿"},
		{English: "goose", Chinese: "鹅"},
		{English: "hen", Chinese: "母鸡"},
		{English: "turkey", Chinese: "火鸡"},
		{English: "lamb", Chinese: "羊羔"},
		{English: "sheep", Chinese: "绵羊"},
		{English: "goat", Chinese: "山羊"},
		{English: "shark", Chinese: "鲨鱼"},
		{English: "seal", Chinese: "海豹"},
	},
}
