package builtin

var Buildings = Group{
	Name: "buildings(builtin)",
	Words: []Word{
		{English: "nest", Chinese: "鸟窝"},
		{English: "stage", Chinese: "舞台"},
		{English: "skyscraper", Chinese: "摩天大楼"},
		{English: "reception", Chinese: "接待处"},
		{English: "corridor", Chinese: "走廊"},
		{English: "shed", Chinese: "小屋"},
		{English: "bath", Chinese: "浴缸", Query: "浴缸"},
		{English: "dustbin", Chinese: "垃圾箱"},
		{English: "radiator", Chinese: "散热器;暖气片"},
		{English: "chimney", Chinese: "烟囱"},
		{English: "doorbell", Chinese: "门铃"},
		{English: "drainpipe", Chinese: "排水管"},
		{English: "fireplace", Chinese: "火炉"},
		{English: "guttering", Chinese: "排水系统"},
		{English: "roof", Chinese: "屋顶"},
		{English: "garage", Chinese: "车库"},
		{English: "shower", Chinese: "淋浴"},
		{English: "road", Chinese: "马路"},
		{English: "path", Chinese: "小路"},
		{English: "beam", Chinese: "梁"},
		{English: "column", Chinese: "柱子"},
		{English: "bridge", Chinese: "桥"},
		{English: "stair", Chinese: "楼梯"},
		{English: "window", Chinese: "窗户"},
		{English: "door", Chinese: "门"},
		{English: "gate", Chinese: "大门"},
		{English: "wall", Chinese: "墙壁"},
		{English: "floor", Chinese: "地板"},
		{English: "ceiling", Chinese: "天花板"},
		{English: "hole", Chinese: "洞"},
		{English: "fence", Chinese: "栅栏"},
		{English: "hedge", Chinese: "树篱"},
	},
}
