package builtin

var BuildingMaterial = Group{
	Name: "building material(builtin)",
	Words: []Word{
		{English: "steam", Chinese: "蒸汽", Query: "水蒸气"},
		{English: "water", Chinese: "水"},
		{English: "brick", Chinese: "砖"},
		{English: "cement", Chinese: "水泥"},
		{English: "concrete", Chinese: "混凝土"},
		{English: "glass", Chinese: "玻璃"},
		{English: "plaster", Chinese: "灰泥"},
		{English: "gravel", Chinese: "碎石"},
		{English: "marble", Chinese: "大理石"},
		{English: "metal", Chinese: "金属"},
		{English: "plastic", Chinese: "塑料"},
		{English: "sand", Chinese: "沙"},
		{English: "stone", Chinese: "石材"},
		{English: "asbestos", Chinese: "石棉"},
		{English: "wood", Chinese: "木材"},
		{English: "cardboard", Chinese: "纸板"},
		{English: "paper", Chinese: "纸"},
		{English: "rubber", Chinese: "橡胶"},
		{English: "clay", Chinese: "黏土"},
		{English: "mud", Chinese: "泥巴"},
		{English: "dust", Chinese: "灰尘"},
		{English: "smoke", Chinese: "烟"},
		{English: "soil", Chinese: "土壤"},
		{English: "charcoal", Chinese: "炭"},
		{English: "coal", Chinese: "煤"},
		{English: "gas", Chinese: "煤气"},
		{English: "petrol", Chinese: "汽油"},
	},
}
