package builtin

var Clothes = Group{
	Name: "clothes(builtin)",
	Words: []Word{
		{English: "apron", Chinese: "围裙"},
		{English: "belt", Chinese: "皮带"},
		{English: "bikini", Chinese: "比基尼", Query: "三点式比基尼"},
		{English: "blouse", Chinese: "女士衬衫(带扣子、比较正式的衬衫)"},
		{English: "boots", Chinese: "靴子"},
		{English: "bow tie", Chinese: "蝴蝶领结"},
		{English: "boxer shorts", Chinese: "四角短裤"},
		{English: "bra", Chinese: "胸罩"},
		{English: "cap", Chinese: "无边帽"},
		{English: "cardigan", Chinese: "开襟羊毛衫"},
		{English: "coat", Chinese: "外套"},
		{English: "dress", Chinese: "连衣裙"},
		{English: "gloves", Chinese: "手套"},
		{English: "hat", Chinese: "有边帽"},
		{English: "jacket", Chinese: "夹克衫"},
		{English: "jeans", Chinese: "牛仔裤"},
		{English: "knickers", Chinese: "（女用）内裤"},
		{English: "overalls", Chinese: "工装裤"},
		{English: "pants", Chinese: "裤子"},
		{English: "pyjamas", Chinese: "睡衣"},
		{English: "raincoat", Chinese: "雨衣"},
		{English: "sandal", Chinese: "凉鞋", Query: "凉鞋"},
		{English: "scarf", Chinese: "围巾"},
		{English: "shirt", Chinese: "衬衫"},
		{English: "shoelace", Chinese: "鞋带"},
		{English: "shoes", Chinese: "鞋子"},
		{English: "shorts", Chinese: "短裤"},
		{English: "skirt", Chinese: "短裙"},
		{English: "slippers", Chinese: "拖鞋"},
		{English: "socks", Chinese: "短袜", Query: "短袜"},
		{English: "stilettos", Chinese: "细高根"},
		{English: "stockings", Chinese: "长筒女袜", Query: "长筒女袜"},
		{English: "suit", Chinese: "西装", Query: "西装套装"},
		{English: "sweater", Chinese: "毛衣"},
		{English: "thong", Chinese: "丁字裤"},
		{English: "tie", Chinese: "领带"},
		{English: "tights", Chinese: "(女用)连裤袜;紧身裤"},
		{English: "tracksuit", Chinese: "运动服"},
		{English: "trainers", Chinese: "运动鞋"},
		{English: "vest", Chinese: "背心"},
		{English: "wellingtons", Chinese: "威灵顿长靴"},
	},
}
