package builtin

var DailyNecessities = Group{
	Name: "daily necessities(builtin)",
	Words: []Word{
		{English: "bandage", Chinese: "绷带"},
		{English: "receipt", Chinese: "收据;发票"},
		{English: "map", Chinese: "地图", Query: "地图"},
		{English: "compass", Chinese: "指南针", Query: "指南针"},
		{English: "battery", Chinese: "电池", Query: "电池"},
		{English: "candle", Chinese: "蜡烛"},
		{English: "envelopes", Chinese: "信封"},
		{English: "glue", Chinese: "胶水", Query: "胶水"},
		{English: "matches", Chinese: "火柴"},
		{English: "needle", Chinese: "针", Query: "缝衣针"},
		{English: "scissors", Chinese: "剪刀"},
		{English: "sellotape", Chinese: "胶带"},
		{English: "stamps", Chinese: "邮票"},
		{English: "tissues", Chinese: "纸巾"},
		{English: "tap", Chinese: "水龙头"},
		{English: "board", Chinese: "板"},
		{English: "mirror", Chinese: "镜子"},
		{English: "lock", Chinese: "锁"},
		{English: "box", Chinese: "盒子"},
		{English: "zipper", Chinese: "拉链"},
		{English: "menu", Chinese: "菜单"},
		{English: "money", Chinese: "钱"},
		{English: "medicine", Chinese: "药"},
		{English: "vase", Chinese: "花瓶"},
	},
}
