package builtin

var Foods = Group{
	Name: "foods(builtin)",
	Words: []Word{
		{English: "lasagne", Chinese: "千层面"},
		{English: "pasta", Chinese: "意大利面"},
		{English: "pizza", Chinese: "意大利薄饼"},
		{English: "hummus", Chinese: "鹰嘴豆泥"},
		{English: "nut", Chinese: "坚果"},
		{English: "peanut", Chinese: "花生"},
		{English: "walnut", Chinese: "胡桃"},
		{English: "muesli", Chinese: "瑞士果蔬燕麦片"},
		{English: "porridge", Chinese: "麦片粥"},
		{English: "toast", Chinese: "烤面包"},
		{English: "baguette", Chinese: "法棍"},
		{English: "quiche", Chinese: "乳蛋饼"},
		{English: "pastry", Chinese: "面粉糕饼"},
		{English: "bacon", Chinese: "熏猪肉"},
		{English: "rice", Chinese: "米饭"},
		{English: "cake", Chinese: "蛋糕"},
		{English: "bread", Chinese: "面包"},
		{English: "sausage", Chinese: "香肠"},
		{English: "sandwich", Chinese: "三明治"},
		{English: "dumplings", Chinese: "饺子"},
		{English: "french fries", Chinese: "薯条"},
		{English: "hamburger", Chinese: "汉堡"},
		{English: "hot dog", Chinese: "热狗"},
		{English: "noodles", Chinese: "面条"},
		{English: "soup", Chinese: "汤"},
		{English: "salad", Chinese: "沙拉"},
	},
}
