package builtin

var InternalBody = Group{
	Name: "internal body(builtin)",
	Words: []Word{
		{English: "brain", Chinese: "大脑"},
		{English: "heart", Chinese: "心脏", Query: "心脏"},
		{English: "intestine", Chinese: "肠道"},
		{English: "kidney", Chinese: "肾脏"},
		{English: "liver", Chinese: "肝"},
		{English: "lung", Chinese: "肺"},
		{English: "oesophagus", Chinese: "食道"},
		{English: "rectum", Chinese: "直肠"},
		{English: "stomach", Chinese: "胃"},
		{English: "windpipe", Chinese: "气管"},
		{English: "clavicle", Chinese: "锁骨"},
		{English: "kneecap", Chinese: "膝盖骨", Query: "膝盖骨"},
		{English: "pelvis", Chinese: "骨盆"},
		{English: "skeleton", Chinese: "骨架"},
		{English: "skull", Chinese: "头盖骨"},
		{English: "spine", Chinese: "脊柱"},
		{English: "blood", Chinese: "血"},
		{English: "mucus", Chinese: "黏液"},
		{English: "phlegm", Chinese: "痰"},
		{English: "saliva", Chinese: "唾液"},
		{English: "semen", Chinese: "精液"},
		{English: "perspiration", Chinese: "汗"},
		{English: "tears", Chinese: "眼泪"},
		{English: "urine", Chinese: "尿液"},
		{English: "vomit", Chinese: "呕吐物"},
		{English: "bone", Chinese: "骨头"},
		{English: "fat", Chinese: "肥胖"},
		{English: "muscle", Chinese: "肌肉"},
		{English: "nerve", Chinese: "神经", Query: "神经系统"},
		{English: "skin", Chinese: "皮肤"},
	},
}
