package builtin

var Locations = Group{
	Name: "locations(builtin)",
	Words: []Word{
		{English: "square", Chinese: "广场", Query: "广场"},
		{English: "street", Chinese: "街道"},
		{English: "cathedral", Chinese: "大教堂"},
		{English: "church", Chinese: "教堂"},
		{English: "mosque", Chinese: "清真寺"},
		{English: "museum", Chinese: "博物馆"},
		{English: "synagogue", Chinese: "犹太教堂"},
		{English: "theatre", Chinese: "剧院"},
		{English: "university", Chinese: "大学"},
		{English: "cemetery", Chinese: "墓地"},
		{English: "stadium", Chinese: "体育场"},
		{English: "port", Chinese: "码头"},
		{English: "airport", Chinese: "机场", Query: "机场俯视图"},
		{English: "orchard", Chinese: "果园"},
		{English: "school", Chinese: "学校"},
		{English: "park", Chinese: "公园"},
		{English: "library", Chinese: "图书馆"},
		{English: "hospital", Chinese: "医院"},
		{English: "cinema", Chinese: "电影院"},
		{English: "farm", Chinese: "农场"},
		{English: "zoo", Chinese: "动物园"},
		{English: "garden", Chinese: "花园"},
		{English: "canteen", Chinese: "餐厅"},
		{English: "gym", Chinese: "体育馆"},
		{English: "factory", Chinese: "工厂"},
		{English: "bank", Chinese: "银行"},
		{English: "village", Chinese: "村庄"},
		{English: "city", Chinese: "城市"},
	},
}
