package builtin

var Mammals = Group{
	Name: "mammals(builtin)",
	Words: []Word{
		{English: "mole", Chinese: "鼹鼠"},
		{English: "otter", Chinese: "海獭"},
		{English: "walrus", Chinese: "海象"},
		{English: "whale", Chinese: "鲸鱼"},
		{English: "dolphin", Chinese: "海豚"},
		{English: "badger", Chinese: "獾"},
		{English: "bat", Chinese: "蝙蝠"},
		{English: "hedgehog", Chinese: "刺猬"},
		{English: "kangaroo", Chinese: "袋鼠"},
		{English: "monkey", Chinese: "猴子"},
		{English: "panda", Chinese: "熊猫"},
		{English: "bear", Chinese: "熊"},
		{English: "lion", Chinese: "狮"},
		{English: "tiger", Chinese: "老虎"},
		{English: "fox", Chinese: "狐狸"},
		{English: "zebra", Chinese: "斑马"},
		{English: "deer", Chinese: "鹿"},
		{English: "giraffe", Chinese: "长颈鹿"},
		{English: "lamb", Chinese: "羊羔"},
		{English: "sheep", Chinese: "绵羊"},
		{English: "goat", Chinese: "山羊"},
		{English: "seal", Chinese: "海豹"},
		{English: "rabbit", Chinese: "兔子"},
		{English: "horse", Chinese: "马"},
		{English: "elephant", Chinese: "大象"},
		{English: "cat", Chinese: "猫"},
		{English: "dog", Chinese: "狗"},
		{English: "pig", Chinese: "猪"},
		{English: "cow", Chinese: "牛"},
		{English: "mouse", Chinese: "小老鼠", Query: "小老鼠"},
		{English: "rat", Chinese: "大老鼠", Query: "大老鼠"},
		{English: "gorilla", Chinese: "大猩猩"},
		{English: "leopard", Chinese: "豹"},
		{English: "rhino", Chinese: "犀牛"},
		{English: "reindeer", Chinese: "驯鹿"},
		{English: "wolf", Chinese: "狼"},
		{English: "bull", Chinese: "公牛"},
		{English: "calf", Chinese: "小牛"},
		{English: "donkey", Chinese: "驴"},
		{English: "foal", Chinese: "驹"},
		{English: "piglet", Chinese: "小猪"},
		{English: "hamster", Chinese: "仓鼠"},
		{English: "squirrel", Chinese: "松鼠"},
		{English: "antelope", Chinese: "羚羊"},
		{English: "camel", Chinese: "骆驼"},
		{English: "hippopotamus", Chinese: "河马"},
		{English: "chimpanzee", Chinese: "黑猩猩"},
	},
}
