package builtin

var Professions = Group{
	Name: "professions(builtin)",
	Words: []Word{
		{English: "sculptor", Chinese: "雕塑家"},
		{English: "nanny", Chinese: "保姆", Query: "保姆"},
		{English: "poet", Chinese: "诗人", Query: "诗人"},
		{English: "waiter", Chinese: "男服务员"},
		{English: "waitress", Chinese: "女服务员"},
		{English: "dancer", Chinese: "舞者"},
		{English: "judge", Chinese: "法官"},
		{English: "sailor", Chinese: "船员"},
		{English: "soldier", Chinese: "军人"},
		{English: "priest", Chinese: "神父"},
		{English: "librarian", Chinese: "图书管理员"},
		{English: "barman", Chinese: "酒保"},
		{English: "barmaid", Chinese: "女酒保"},
		{English: "carpenter", Chinese: "木匠"},
		{English: "vet", Chinese: "兽医"},
		{English: "dentist", Chinese: "牙医"},
		{English: "tailor", Chinese: "裁缝"},
		{English: "butcher", Chinese: "肉贩"},
		{English: "barber", Chinese: "理发师"},
		{English: "baker", Chinese: "面包师傅"},
		{English: "telephonist", Chinese: "接听员"},
		{English: "actor", Chinese: "男演员", Query: "男演员"},
		{English: "actress", Chinese: "女演员", Query: "女演员"},
		{English: "pilot", Chinese: "飞行员"},
		{English: "engineer", Chinese: "工程师"},
		{English: "doctor", Chinese: "医生"},
		{English: "nurse", Chinese: "护士"},
		{English: "driver", Chinese: "司机"},
		{English: "farmer", Chinese: "农民"},
		{English: "singer", Chinese: "歌唱家"},
		{English: "teacher", Chinese: "教师"},
		{English: "student", Chinese: "学生"},
		{English: "reporter", Chinese: "记者"},
		{English: "programmer", Chinese: "程序员"},
		{English: "athlete", Chinese: "运动员"},
		{English: "chef", Chinese: "厨师"},
	},
}
