package builtin

var Sports = Group{
	Name: "sports(builtin)",
	Words: []Word{
		{English: "archery", Chinese: "射箭"},
		{English: "badminton", Chinese: "羽毛球"},
		{English: "baseball", Chinese: "棒球"},
		{English: "basketball", Chinese: "篮球"},
		{English: "boxing", Chinese: "拳击"},
		{English: "climbing", Chinese: "攀岩"},
		{English: "cricket", Chinese: "板球"},
		{English: "fishing", Chinese: "钓鱼"},
		{English: "golf", Chinese: "高尔夫球"},
		{English: "gymnastics", Chinese: "体操"},
		{English: "hiking", Chinese: "徒步"},
		{English: "hockey", Chinese: "曲棍球"},
		{English: "hunting", Chinese: "狩猎"},
		{English: "jogging", Chinese: "慢跑"},
		{English: "judo", Chinese: "柔道"},
		{English: "karate", Chinese: "空手道"},
		{English: "netball", Chinese: "无板篮球"},
		{English: "rowing", Chinese: "赛艇"},
		{English: "rugby", Chinese: "橄榄球"},
		{English: "running", Chinese: "跑步"},
		{English: "sailing", Chinese: "帆船运动"},
		{English: "shooting", Chinese: "射击"},
		{English: "skiing", Chinese: "滑雪"},
		{English: "snooker", Chinese: "斯诺克"},
		{English: "surfing", Chinese: "冲浪"},
		{English: "swimming", Chinese: "游泳"},
		{English: "tennis", Chinese: "网球"},
		{English: "volleyball", Chinese: "排球"},
		{English: "walking", Chinese: "走路"},
		{English: "wrestling", Chinese: "摔跤"},
		{English: "yoga", Chinese: "瑜伽"},
		{English: "soccer", Chinese: "足球"},
	},
}
