package builtin

var Tools = Group{
	Name: "tools(builtin)",
	Words: []Word{
		{English: "tweezer", Chinese: "镊子"},
		{English: "chisel", Chinese: "凿子", Query: "凿子"},
		{English: "hammer", Chinese: "钉锤"},
		{English: "drill", Chinese: "钻子"},
		{English: "file", Chinese: "锉刀", Query: "锉刀"},
		{English: "ladder", Chinese: "梯子"},
		{English: "pliers", Chinese: "钳子"},
		{English: "saw", Chinese: "锯子"},
		{English: "screwdriver", Chinese: "螺丝起子"},
		{English: "spanner", Chinese: "板手"},
		{English: "bolt", Chinese: "螺栓", Query: "螺栓"},
		{English: "nail", Chinese: "钉", Query: "钉子"},
		{English: "nut", Chinese: "螺母", Query: "螺母"},
		{English: "screw", Chinese: "螺丝"},
		{English: "washer", Chinese: "垫圈", Query: "垫圈"},
		{English: "brick", Chinese: "砖"},
		{English: "cement", Chinese: "水泥"},
		{English: "plaster", Chinese: "灰泥"},
		{English: "string", Chinese: "绳子"},
		{English: "tape", Chinese: "带子"},
		{English: "tile", Chinese: "地砖"},
		{English: "wire", Chinese: "金属丝"},
		{English: "pipe", Chinese: "管子"},
	},
}
