package builtin

var Vegetables = Group{
	Name: "vegetables(builtin)",
	Words: []Word{
		{English: "paprika", Chinese: "红辣椒"},
		{English: "artichoke", Chinese: "洋蓟"},
		{English: "asparagus", Chinese: "芦笋"},
		{English: "beet", Chinese: "甜菜"},
		{English: "broccoli", Chinese: "西兰花"},
		{English: "cabbage", Chinese: "卷心菜"},
		{English: "carrot", Chinese: "葫萝卜"},
		{English: "cauliflower", Chinese: "菜花;花椰菜"},
		{English: "celery", Chinese: "芹菜"},
		{English: "corn", Chinese: "玉米"},
		{English: "courgette", Chinese: "西葫芦;小胡瓜"},
		{English: "cucumber", Chinese: "黄瓜"},
		{English: "garlic", Chinese: "蒜"},
		{English: "ginger", Chinese: "姜"},
		{English: "leek", Chinese: "大葱"},
		{English: "lettuce", Chinese: "生菜"},
		{English: "mushroom", Chinese: "蘑菇"},
		{English: "onion", Chinese: "洋葱"},
		{English: "pea", Chinese: "豌豆"},
		{English: "pepper", Chinese: "辣椒"},
		{English: "potato", Chinese: "土豆"},
		{English: "pumpkin", Chinese: "南瓜"},
		{English: "radish", Chinese: "小萝卜"},
		{English: "spinach", Chinese: "菠菜"},
		{English: "tomato", Chinese: "西红柿"},
		{English: "eggplant", Chinese: "茄子"},
	},
}
